/* Persistencia Supabase sin dependencias: funciona desde GitHub Pages con RLS. */
let cloudSession=null, cloudReady=false, cloudSaving=false;
const api=window.SUPABASE_URL, key=window.SUPABASE_PUBLISHABLE_KEY;
function syncStatus(text,error=false){let el=document.getElementById('milan-sync-status');if(!el){el=document.createElement('div');el.id='milan-sync-status';el.style.cssText='position:fixed;left:16px;bottom:16px;z-index:40;padding:9px 12px;border-radius:7px;color:#fff;font:12px system-ui;box-shadow:0 2px 8px #0003';document.body.append(el)}el.style.background=error?'#a72d2d':'#287c58';el.textContent=text}
function readableError(e){try{let x=JSON.parse(e.message);return x.message||x.hint||'Error de Supabase'}catch{return e.message||'Error de conexión'}}
async function sb(path,opts={}){let headers={apikey:key,'Content-Type':'application/json',...(opts.headers||{})};if(cloudSession?.access_token)headers.Authorization=`Bearer ${cloudSession.access_token}`;let r=await fetch(api+path,{...opts,headers});let t=await r.text();if(!r.ok)throw new Error(t||`Error ${r.status}`);return t?JSON.parse(t):null}
const getRows=t=>sb(`/rest/v1/${t}?select=*`);
async function cloudLoad(){let tutor=role()==='tutor';let [owners,pets,records,vaccinations,catalog]=await Promise.all([tutor?Promise.resolve([]):getRows('owners'),getRows('pets'),getRows('medical_records'),getRows('vaccinations'),tutor?Promise.resolve([]):getRows('vaccine_catalog')]);return {owners:owners.map(o=>({id:o.id,name:o.name,dni:o.dni,phone:o.phone,whatsapp:o.whatsapp,email:o.email,address:o.address,city:o.city,notes:o.notes})),pets:pets.map(p=>({id:p.id,name:p.name,species:p.species,breed:p.breed,sex:p.sex,birth:p.birth_date,weight:p.weight,color:p.color,microchip:p.microchip,photo:p.photo_path,owner:p.owner_id,status:p.status,notes:p.notes})),records:records.map(r=>({id:r.id,pet:r.pet_id,date:r.visit_date,reason:r.reason,anamnesis:r.anamnesis,exam:r.physical_exam,weight:r.weight,temp:r.temperature,diagnosis:r.diagnosis,treatment:r.treatment,medication:r.medication,instructions:r.instructions,notes:r.notes,vet:r.veterinarian})),vaccinations:vaccinations.map(v=>({id:v.id,pet:v.pet_id,type:v.vaccine_name,applied:v.applied_date,next:v.next_dose_date,dose:v.dose_number,lot:v.lot,maker:v.manufacturer,vet:v.veterinarian,notes:v.notes})),catalog:catalog.map(v=>v.name),logs:[],reminderDays:30,staffUsers:db.staffUsers||[]}}
async function upsert(table,rows){if(!rows.length)return;await sb(`/rest/v1/${table}?on_conflict=id`,{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(rows)})}
async function removeMissing(table,ids){let remote=await getRows(table);for(let r of remote)if(!ids.includes(r.id))await sb(`/rest/v1/${table}?id=eq.${r.id}`,{method:'DELETE',headers:{Prefer:'return=minimal'}})}
async function cloudSave(){if(!cloudReady||cloudSaving||!cloudSession)return;cloudSaving=true;syncStatus('Guardando en Supabase…');try{let uid=cloudSession.user.id;let owners=db.owners.map(o=>({id:o.id,user_id:uid,name:o.name,dni:o.dni,phone:o.phone,whatsapp:o.whatsapp,email:o.email,address:o.address,city:o.city,notes:o.notes}));await upsert('owners',owners);await removeMissing('owners',owners.map(x=>x.id));let pets=db.pets.map(p=>({id:p.id,user_id:uid,owner_id:p.owner,name:p.name,species:p.species,breed:p.breed,sex:p.sex,birth_date:p.birth||null,weight:p.weight||null,color:p.color,microchip:p.microchip,photo_path:p.photo,status:p.status,notes:p.notes}));await upsert('pets',pets);await removeMissing('pets',pets.map(x=>x.id));let records=db.records.map(r=>({id:r.id,user_id:uid,pet_id:r.pet,visit_date:r.date,reason:r.reason,anamnesis:r.anamnesis,physical_exam:r.exam,weight:r.weight||null,temperature:r.temp||null,diagnosis:r.diagnosis,treatment:r.treatment,medication:r.medication,instructions:r.instructions,notes:r.notes,veterinarian:r.vet}));await upsert('medical_records',records);await removeMissing('medical_records',records.map(x=>x.id));let vaccinations=db.vaccinations.map(v=>({id:v.id,user_id:uid,pet_id:v.pet,vaccine_name:v.type,applied_date:v.applied||null,next_dose_date:v.next,dose_number:v.dose||null,lot:v.lot,manufacturer:v.maker,veterinarian:v.vet,notes:v.notes}));await upsert('vaccinations',vaccinations);await removeMissing('vaccinations',vaccinations.map(x=>x.id));let catalog=db.catalog.map(name=>({id:crypto.randomUUID(),user_id:uid,name}));await sb(`/rest/v1/vaccine_catalog?user_id=eq.${uid}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});await upsert('vaccine_catalog',catalog);syncStatus('✓ Guardado en Supabase')}catch(e){console.error(e);let msg=readableError(e);syncStatus('Error Supabase: '+msg,true);toast('No se guardó: '+msg)}finally{cloudSaving=false}}
async function remoteLogin(e){e.preventDefault();let f=new FormData(e.target);try{let r=await sb('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:f.get('email'),password:f.get('password')})});cloudSession=r;localStorage.setItem('milanSupabaseSession',JSON.stringify(r));let profiles=await sb(`/rest/v1/profiles?id=eq.${r.user.id}&select=*`);if(!profiles[0])throw new Error('La cuenta existe pero aún no tiene perfil/rol asignado.');let p=profiles[0];sessionStorage.setItem('milanAuth','1');sessionStorage.setItem('milanUser',JSON.stringify({id:r.user.id,name:p.full_name||r.user.email,role:p.role,ownerId:p.owner_id}));db=await cloudLoad();localStorage.setItem(K,JSON.stringify(db));cloudReady=true;view=p.role==='tutor'?'portal':'dashboard';render();syncStatus('✓ Conectado a Supabase');toast('Sesión iniciada y datos cargados')}catch(err){console.error(err);let msg=readableError(err);syncStatus('Error de acceso: '+msg,true);toast('No fue posible iniciar sesión: '+msg) }}
function login(){document.getElementById('app').innerHTML=`<div class="login"><div class="loginbox"><img src="${logo}" alt="MILÁN"><h1>Gestión Veterinaria</h1><p class="sub">Acceso seguro con Supabase</p><form class="form" onsubmit="remoteLogin(event)"><label>Email<input name="email" required type="email" placeholder="usuario@correo.com"></label><label>Contraseña<input name="password" required type="password" placeholder="••••••••"></label><button class="btn gold">Ingresar</button></form><hr style="border:0;border-top:1px solid var(--line);margin:20px 0"><p class="small">¿Todavía no creaste usuarios en Supabase? Usá el acceso DEMO mientras se configura.</p><button class="btn ghost" onclick="loginDemoMode()">Acceder al modo DEMO</button></div></div>`}
function loginDemoMode(){cloudReady=false;cloudSession=null;window.loginDemoOriginal()}
window.loginDemoOriginal=window.loginDemoOriginal||function(){document.getElementById('app').innerHTML=`<div class="login"><div class="loginbox"><img src="${logo}" alt="MILÁN"><h1>Modo DEMO</h1><form class="form" onsubmit="demoLogin(event)"><label>Tipo de acceso<select name="kind" onchange="toggleTutor(this.value)"><option value="staff">Personal de la clínica</option><option value="tutor">Portal de tutor</option></select></label><label id="staffSelect">Usuario<select name="user">${db.staffUsers.map(u=>`<option value="${u.id}">${esc(u.name)} — ${u.role}</option>`).join('')}</select></label><label id="tutorSelect" class="hidden">Tutor<select name="owner">${db.owners.map(o=>`<option value="${o.id}">${esc(o.name)}</option>`).join('')}</select></label><label>Contraseña<input required type="password"></label><button class="btn gold">Ingresar DEMO</button></form></div></div>`};
(async()=>{let cached=JSON.parse(localStorage.getItem('milanSupabaseSession')||'null');if(!cached){login();return}try{cloudSession=cached;let user=await sb('/auth/v1/user');cloudSession.user=user;let profiles=await sb(`/rest/v1/profiles?id=eq.${user.id}&select=*`);if(!profiles[0])throw Error();let p=profiles[0];sessionStorage.setItem('milanAuth','1');sessionStorage.setItem('milanUser',JSON.stringify({id:user.id,name:p.full_name||user.email,role:p.role,ownerId:p.owner_id}));db=await cloudLoad();cloudReady=true;view=p.role==='tutor'?'portal':'dashboard';render()}catch{localStorage.removeItem('milanSupabaseSession');login()}})();
